baseurl = "https://life-update.netlify.app/"
languageCode = "ja-jp"
title = "Life update"
# Enable comments by entering your Disqus shortname
disqusShortname = "https-life-update-netlify-com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus"
# Comment the themesDir option if you use this theme in production
#themesDir = "../.."

[permalinks]
    post = "/:year/:month/:day/:filename"


[params]
    # Tell me who you are
    author = "mizuti"
    bio = "そこらへんの人"
    location = "Japan"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](https://github.com/ppoffice)."
    avatar = "avatar.png"
    # Enter your email address to display your Gravatar icon in the profile. If not set the theme
    # will fallback to the avatar.
    gravatar = "mizuti7802@gmail.com"
    logo = "logo.png"
    disable_mathjax = false # set to true to disable MathJax

    # define which types of pages should be shown. By default the type with the most regular pages
    mainSections = ["post"]

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = ["css/custom.css"]
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option thes
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "ライブ記"
    link   = "/live"

[[params.menu]]
    before = false
    label  = "デスチャ攻略"
    link   = "/game/descha"

#[[params.menu]]
#    before = false
#    label  = "Tags"
#    link   = "tags/"

#[[params.menu]]
#    before = false
#    label  = "Categories"
#    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/mizuti69"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "https://github.com/mizuti69"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""
    mailto          = "mizuti7802@gmail.com"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

# Enable markdown in html code for v0.66 over
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
